openapi: "3.1.0"
info:
  title: "example_2025 API"
  description: "example_2025 API"
  version: "1.0.0"
servers:
- url: "https://example_2025"
paths:
  /api/clients/login:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestModel"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    status: "User with this email and password doesn't exist"
                Example#2:
                  description: ""
                  value:
                    status: "User with this email and password doesn't exist"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/LoginResponseModel"
  /api/clients/register:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequestModel"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    status: "User with this email already exists"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/LoginResponseModel"
  /api/companies/login:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestModel"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    status: "User with this email and password doesn't exist"
                Example#2:
                  description: ""
                  value:
                    status: "User with this email and password doesn't exist"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/LoginResponseModel"
  /api/companies/register:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterCompanyRequestModel"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    status: "User with this email already exists"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/LoginResponseModel"
  /api/offers/client:
    get:
      description: ""
      parameters:
      - name: "limit"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "offset"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    status: "You are not client"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    status: "Wrong offset"
                Example#2:
                  description: ""
                  value:
                    status: "Wrong limit"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/GetOfferResponseModel"
  /api/offers/company:
    get:
      description: ""
      parameters:
      - name: "limit"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "offset"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    status: "You are not company"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    status: "Wrong offset"
                Example#2:
                  description: ""
                  value:
                    status: "Wrong limit"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/GetOfferResponseModel"
  /api/offers/create:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRequestModel"
        required: true
      responses:
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    status: "Authorized as client"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    status: "Company not found"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                type: "object"
  /api/ping:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    LoginRequestModel:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
      required:
      - "email"
      - "password"
    ErrorResponse:
      type: "object"
      properties:
        status:
          type: "string"
      required:
      - "status"
    LoginResponseModel:
      type: "object"
      properties:
        token:
          type: "string"
      required:
      - "token"
    RegisterRequestModel:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"
      required:
      - "firstName"
      - "lastName"
      - "email"
      - "password"
    RegisterCompanyRequestModel:
      type: "object"
      properties:
        name:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"
      required:
      - "name"
      - "email"
      - "password"
    GetOfferResponseModel:
      type: "object"
      properties:
        id:
          type: "string"
        company_id:
          type: "string"
        company_name:
          type: "string"
        title:
          type: "string"
        description:
          type: "string"
        discount:
          type: "number"
          format: "double"
        start_date:
          type: "string"
        end_date:
          type: "string"
      required:
      - "id"
      - "company_id"
      - "company_name"
      - "title"
      - "description"
      - "start_date"
      - "end_date"
    CreateRequestModel:
      type: "object"
      properties:
        title:
          type: "string"
        description:
          type: "string"
        discount:
          type: "number"
          format: "double"
        startDate:
          type: "string"
        endDate:
          type: "string"
      required:
      - "title"
      - "description"
      - "startDate"
      - "endDate"