include:
    - "jobs/build.yaml"
    - "jobs/docker.yaml"
    - "jobs/rules.yaml"
    - "jobs/test.yaml"

.global-variables:
  variables:
    SSH_USER: "$ENV_SSH_USER"
    SSH_HOST: "$ENV_SSH_HOST"
    SSH_PRIVATE_KEY_BASE64: "$ENV_PRIVATE_KEY_BASE64"

stages:
  - test
  - build
  - deploy

test:
  stage: test
  extends:
    - .test
    - .rules-merge-or-master


build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .global-variables
    - .rules-master
  variables:
    OPT_DOCKER: "-p 80:80"
