x-common: &env-common
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_URL: "jdbc:postgresql://postgres:5432/prod"
    POSTGRES_DB: prod


services:
  app:
    image: gitlab.prodcontest.ru:5050/team-10/backend
    restart: unless-stopped
    networks:
      - main
    <<: *env-common
  postgres:
    image: postgres:17.3
    restart: unless-stopped
    networks:
      - main
    ports:
      - "80:8080"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
    <<: *env-common


volumes:
  pg_data:

networks:
  main:
    driver: bridge
