---
.build:
  image: 
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  stage: build
  variables:
    DOCKERFILE_PATH: Dockerfile
    DOCKER_CONFIG: /kaniko/.docker
    CONTEXT: $CI_PROJECT_DIR
    IMAGE_TAG: "latest"
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$IMAGE_TAG
    REGISTRY_USER: $CI_REGISTRY_USER
    REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    REGISTRY_URL: $CI_REGISTRY
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}},\"https://index.docker.io/v1/\":{\"auth\":\"a29seWFrb3QzMzpkY2tyX3BhdF8xTzM3S1k1MnM0VXRMTG44bmxLSlg2NzZOOUk=\"}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CONTEXT}"
      --dockerfile "${CI_PROJECT_DIR}/${DOCKERFILE_PATH}"
      --destination "${IMAGE_NAME}"
      --cache=True
